# -*- coding: utf-8 -*-
"""laba 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18c19q4Kvn_N8FsXDKNJpSkO5UmilFnHA
"""

months = ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"]
num = int(input("Введите номер месяца (1-12): "))

if 1 <= num <= 12:
    print("Месяц:", months[num - 1])
else:
    print("Введите число от 1 до 12.")

number = int(input("Введите число: "))
print(f"{number} - {'четное' if number % 2 == 0 else 'нечетное'} число.")

N = int(input("Введите число: "))
if N > 40:
  print("stonks")
else:
  print("not stonks")

def is_year_leap(year):
  return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)
year = int(input("Введите год: "))
if is_year_leap(year):
    print(f"{year} - високосный год")
else:
    print(f"{year} - не високосный год")

def is_prime(n):
    if n <= 1:
        return False
    elif n <= 3:
        return True
    elif n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True
number = int(input("Введите число: "))
if is_prime(number):
  print(f"{number} - простое число")
else:
  print(f"{number} - сложное число")

a = int(input("Введите число: "))
b = int(input("Введите число: "))
if a > b * 3.6 or (-138 // 2) ** 1.3 <= b <= abs((-69 // (28 ** 5.1)) * 4):
    a, b = b, a

print("После обмена:")
print("Первая переменная:", a)
print("Вторая переменная:", b)

numbers = []
even_count = negative_count = in_range_count = 0

for _ in range(5):
    num = int(input("Введите число: "))
    numbers.append(num)
    even_count += num % 2 == 0
    negative_count += num < 0
    in_range_count += -256 <= num <= 1024

unique_numbers = len(set(numbers))

print("Количество уникальных чисел:", unique_numbers)
print("Количество четных чисел:", even_count)
print("Количество отрицательных чисел:", negative_count)
print("Количество чисел в диапазоне [-256; 1024]:", in_range_count)

